#!/usr/bin/env python3
"""Generate src/blackbody_lut.h: linear-sRGB radiance of a Planck spectrum.

For each temperature T (log-spaced) the Planck spectral radiance B_lambda(T)
is integrated against the CIE 1931 2-degree colour-matching functions
(Wyman, Sloan & Shirley 2013 multi-lobe fit) and converted XYZ -> linear sRGB
(D65 white point, i.e. a camera white-balanced to daylight).

The result keeps ABSOLUTE photometric scale (normalized so Y(6500 K) = 1):
because I_nu / nu^3 is Lorentz invariant, a Planck source at T seen with
redshift factor g is exactly a Planck spectrum at g*T, so looking up
rgb(g*T) gives both the observed colour and the observed visible-band
brightness -- no separate g^3 / g^4 factor is needed.

Out-of-gamut colours (very cool, very red T) are desaturated toward their
own luminance until no channel is negative (hue and luminance preserved).

Usage:  python3 tools/gen_blackbody_lut.py > src/blackbody_lut.h
"""
import math

T_MIN, T_MAX, N = 800.0, 40000.0, 128


def lobe(lam, mu, s1, s2):
    s = s1 if lam < mu else s2
    t = (lam - mu) / s
    return math.exp(-0.5 * t * t)


def cmf(lam):
    x = (1.056 * lobe(lam, 599.8, 37.9, 31.0) + 0.362 * lobe(lam, 442.0, 16.0, 26.7)
         - 0.065 * lobe(lam, 501.1, 20.4, 26.2))
    y = 0.821 * lobe(lam, 568.8, 46.9, 40.5) + 0.286 * lobe(lam, 530.9, 16.3, 31.1)
    z = 1.217 * lobe(lam, 437.0, 11.8, 36.0) + 0.681 * lobe(lam, 459.0, 26.0, 13.8)
    return x, y, z


def planck(lam_nm, T):
    lam = lam_nm * 1e-9
    c2 = 1.4387769e-2  # h c / k  [m K]
    return 1.0 / (lam ** 5 * (math.exp(c2 / (lam * T)) - 1.0))


def xyz(T):
    X = Y = Z = 0.0
    for lam in range(360, 831):
        b = planck(float(lam), T)
        cx, cy, cz = cmf(float(lam))
        X += b * cx; Y += b * cy; Z += b * cz
    return X, Y, Z


def to_srgb(X, Y, Z):
    r = 3.2406 * X - 1.5372 * Y - 0.4986 * Z
    g = -0.9689 * X + 1.8758 * Y + 0.0415 * Z
    b = 0.0557 * X - 0.2040 * Y + 1.0570 * Z
    lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
    m = min(r, g, b)
    if m < 0.0 and lum > 0.0:
        s = lum / (lum - m)          # scale chroma so min channel -> 0
        r, g, b = (lum + (c - lum) * s for c in (r, g, b))
    return max(r, 0.0), max(g, 0.0), max(b, 0.0)


def main():
    ref = to_srgb(*xyz(6500.0))
    yref = 0.2126 * ref[0] + 0.7152 * ref[1] + 0.0722 * ref[2]
    rows = []
    for i in range(N):
        T = T_MIN * (T_MAX / T_MIN) ** (i / (N - 1))
        r, g, b = to_srgb(*xyz(T))
        rows.append((T, r / yref, g / yref, b / yref))

    print("#pragma once")
    print("// Generated by tools/gen_blackbody_lut.py -- do not edit by hand.")
    print("// Linear-sRGB (D65) radiance of a Planck spectrum, CIE 1931 2-deg")
    print("// observer, absolute scale with luminance Y(6500 K) = 1.")
    print("// Entry i is at T = BB_LUT_TMIN * (BB_LUT_TMAX/BB_LUT_TMIN)^(i/(N-1)).")
    print("#include <cuda_runtime.h>")
    print()
    print(f"#define BB_LUT_N    {N}")
    print(f"#define BB_LUT_TMIN {T_MIN:.1f}f")
    print(f"#define BB_LUT_TMAX {T_MAX:.1f}f")
    print()
    print("__constant__ float c_bbLut[BB_LUT_N * 3] = {")
    for T, r, g, b in rows:
        print(f"    {r:.6e}f, {g:.6e}f, {b:.6e}f,  // {T:8.1f} K")
    print("};")


if __name__ == "__main__":
    main()
